import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import ThemeContextProvider from "./theme-provider";

const poppins = Poppins({
  style: "normal",
  weight: "500",
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Controlle de projetos da integração",
  description: "Generated by Peixola",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <Suspense fallback={<div>Loading...</div>}>
        <body className={poppins.className}>
          <ThemeContextProvider>{children}</ThemeContextProvider>
        </body>
      </Suspense>
    </html>
  );
}
